uah_gestor_actividades_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: UAHGestorActividadesBundle:Default:index }
fp_openid_security:
    resource: "@FpOpenIdBundle/Resources/config/routing/security.xml"