parameters:
    UAHGestorActividadesBundle.db.table_prefix: UAH_GAT_
services:
            UAHGestorActividadesBundle.tblprefix_subscriber:
                class: UAH\GestorActividadesBundle\Subscriber\TablePrefixSubscriber
                arguments: [%UAHGestorActividadesBundle.db.table_prefix%]
                tags:
                    - { name: doctrine.event_subscriber }    