#!/bin/bash
# .openshift/action_hooks/deploy

export COMPOSER_HOME="$OPENSHIFT_DATA_DIR/.composer"
 
if [ ! -f "$OPENSHIFT_DATA_DIR/composer.phar" ]; then
    curl -s https://getcomposer.org/installer | php -- --install-dir=$OPENSHIFT_DATA_DIR
else
    php $OPENSHIFT_DATA_DIR/composer.phar self-update
fi
 
unset GIT_DIR 
cd $OPENSHIFT_REPO_DIR

php $OPENSHIFT_DATA_DIR/composer.phar install
 
php $OPENSHIFT_REPO_DIR/app/console cache:clear --env=dev
pwd
cd $OPENSHIFT_REPO_DIR 
chmod -R 0777 app/cache
chmod -R 0777 app/logs
 
rm -r $OPENSHIFT_REPO_DIR/php
ln -s $OPENSHIFT_REPO_DIR/web $OPENSHIFT_REPO_DIR/php
 
rm -r $OPENSHIFT_REPO_DIR/php
ln -s $OPENSHIFT_REPO_DIR/web $OPENSHIFT_REPO_DIR/php
 
php $OPENSHIFT_REPO_DIR/app/console doctrine:schema:update --force
php $OPENSHIFT_REPO_DIR/app/console doctrine:fixtures:load --force
