#!/bin/bash
# .openshift/action_hooks/deploy

export COMPOSER_HOME="$OPENSHIFT_DATA_DIR/.composer"
 
if [ ! -f "$OPENSHIFT_DATA_DIR/composer.phar" ]; then
    curl -s https://getcomposer.org/installer | php -- --install-dir=$OPENSHIFT_DATA_DIR
else
    php $OPENSHIFT_DATA_DIR/composer.phar self-update
fi
 
unset GIT_DIR 
cd $OPENSHIFT_REPO_DIR
php $OPENSHIFT_DATA_DIR/composer.phar install
 
php $OPENSHIFT_REPO_DIR/app/console cache:clear --env=dev

#Arreglo la cache
chmod -R 0777 $OPENSHIFT_REPO_DIR/app/dev/cache
chmod -R 0777 $OPENSHIFT_REPO_DIR/app/dev/logs

if [ -f "$OPENSHIFT_REPO_DIR/php" ]; then
 	rm -r $OPENSHIFT_REPO_DIR/php
	ln -s $OPENSHIFT_REPO_DIR/web $OPENSHIFT_REPO_DIR/php
fi
if [ ! -d "$OPENSHIFT_REPO_DIR/web/uploads/images"]
	mkdir -p $OPENSHIFT_REPO_DIR/web/uploads/images
fi
chmod -R 0777 $OPENSHIFT_REPO_DIR/web/uploads
php $OPENSHIFT_REPO_DIR/app/console doctrine:schema:update --force
php $OPENSHIFT_REPO_DIR/app/console doctrine:fixtures:load 
