#!/bin/bash
# .openshift/action_hooks/deploy
echo 'aqui';	
export COMPOSER_HOME="$OPENSHIFT_DATA_DIR/.composer"
 
if [ ! -f "$OPENSHIFT_DATA_DIR/composer.phar" ]; then
    curl -s https://getcomposer.org/installer | php -- --install-dir=$OPENSHIFT_DATA_DIR
else
    php $OPENSHIFT_DATA_DIR/composer.phar self-update
fi
echo 'aqui1'
unset GIT_DIR 

php $OPENSHIFT_DATA_DIR/composer.phar install
 
php $OPENSHIFT_REPO_DIR/app/console cache:clear --env=dev

#Arreglo la cache
chmod -R 0777 $OPENSHIFT_REPO_DIR/app/dev/cache
chmod -R 0777 $OPENSHIFT_REPO_DIR/app/dev/logs

#Creo la carpeta de imagenes subidas
if [ ! -f "$OPENSHIFT_REPO_DIR/web/upload/images" ]; then
    mkdir -p $OPENSHIFT_REPO_DIR/web/upload/images
fi

if [ -f "$OPENSHIFT_REPO_DIR/php" ]; then
	rm -r $OPENSHIFT_REPO_DIR/php
	ln -s $OPENSHIFT_REPO_DIR/web $OPENSHIFT_REPO_DIR/php
fi

 
php $OPENSHIFT_REPO_DIR/app/console doctrine:schema:update --force
php $OPENSHIFT_REPO_DIR/app/console doctrine:fixtures:load 
