imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        group:
            type: group
            members: [fileStream, loggly]
        fileStream:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: info            
        loggly:
            type: loggly
            token: b962de48-3388-4912-b859-b705d9e12e41
            level: info
            channels: ~
            tags: ['prod']
        main:
            type: fingers_crossed
            action_level: error
            handler: group
            channels: ["!event"]        

