imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        group:
            type: group
            members: [fileStream, loggly]
        fileStream:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: "!event"
        loggly:
            type: loggly
            token: b962de48-3388-4912-b859-b705d9e12e41
            level: debug
            channels: ~
            tags: ['dev']
        main:
            type: fingers_crossed
            action_level: error
            handler: group
            channels: "!event"
        firephp:
            type:  firephp
            level: info
        chromephp:
            type:  chromephp
            level: info

assetic:
    use_controller: true
#bazinga_faker: 
#    orm: doctrine
#    locale: es_ES
#    seed: 1
#    entities:
#        UAH\GestorActividadesBundle\Entity\TuibPersonaUser:
#            number: 5
#swiftmailer:
#    delivery_address: me@example.com
