imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @UAHGestorActividadesBundle/Resources/config/parameters.yml }
    - { resource: params.php }
framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true
    #Aqui va 
    session:
        handler_id: session.handler.doctrine

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    cache:  false
# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: true
    bundles:        [UAHGestorActividadesBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
        uglifyjs2:
            # the path to the uglifyjs executable
            bin: %kernel.root_dir%/../app/Resources/node_modules/uglify-js/bin/uglifyjs
        uglifycss:
            bin: %kernel.root_dir%/../app/Resources/node_modules/uglifycss/uglifycss
        lessphp:
            file: %kernel.root_dir%/../vendor/oyejorge/less.php/lessc.inc.php
            apply_to: "\.less$"


# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8            
            
            # if using pdo_sqlite as your database driver, add the path in parameters.yml
            # e.g. database_path: "%kernel.root_dir%/data/data.db3"
            # path:     "%database_path%"
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
doctrine_migrations:
    dir_name: %kernel.root_dir%/DoctrineMigrations
    namespace: Application\Migrations
    table_name: UAH_GAT_MIGRATION_VERSIONS
    name: Migraciones entre versiones
# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

sensio_framework_extra:
    router:  { annotations: true }
    security:   { annotations: true }
     
parameters:
    doctrine.session.db_options:
        db_table:    UAH_GAT_Session
        db_id_col:   session_id
        db_data_col: session_value
        db_time_col: session_time
    vendor_dir: %kernel.root_dir%/../src/UAH/GestorActividadesBundle/Resources/public/vendor    
    pdf_dir: %kernel.root_dir%/../web/upload/pdf/
    elements_per_page: 7
    
services:
    session.handler.doctrine:
        # Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        class:     UAH\GestorActividadesBundle\Services\DoctrineSessionHandler 
        arguments: ["@doctrine.dbal.default_connection", "%doctrine.session.db_options%"]
braincrafted_bootstrap:
    output_dir: bootstrap
    assets_dir: %vendor_dir%/bootstrap
    jquery_path: %vendor_dir%/jquery/dist/jquery.js
    less_filter: lessphp # "less", "lessphp" or "none"
    auto_configure:
        assetic: true
        twig: true
        knp_menu: true
        knp_paginator: true
    customize:
        variables_file: ~
        bootstrap_output: %kernel.root_dir%/Resources/less/bootstrap.less
        bootstrap_template: BraincraftedBootstrapBundle:Bootstrap:bootstrap.less.twig
fp_open_id:
    db_driver: orm
    identity_class: UAH\GestorActividadesBundle\Entity\OpenIdIdentity     
knp_snappy:
    pdf:
        enabled:    true
        binary:     %kernel.root_dir%/../wkhtmltopdf/wkhtmltopdf
        options:    
            load-error-handling: ignore
            print-media-type: true
            disable-smart-shrinking: true
            page-width: 21cm
            page-height: 27cm
            stop-slow-scripts: true
            load-error-handling: ignore
            dpi: 96
            javascript-delay: 100            
            
        # ['--print-media-type','--disable-smart-shrinking','--page-width 21cm','--page-height 27cm','--dpi 96']
    image:
        enabled:    true
        binary:     /home/xokas/pfc/wkhtmltopdf/wkhtmltoimage
        options:    []    
monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: warning
            handler: file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            channels: ["!event"]