UAHGestorActividadesBundle_yml:
    resource: "@UAHGestorActividadesBundle/Resources/config/routing.yml"
UAHGestorActividadesBundle_annotation:
    resource: "@UAHGestorActividadesBundle/Controller"
    type: annotation
fp_openid_security:
    resource: "@FpOpenIdBundle/Resources/config/routing/security.xml" 
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
EndroidQrCodeBundle:
    resource:   "@EndroidQrCodeBundle/Controller/"
    type:       annotation
    prefix:     /qrcode
my_barcode_playground:
    resource: "@MopaBarcodeBundle/Resources/config/routing/barcode_playground.yml"
    prefix:   /    
