<?php

namespace UAH\GestorActividadesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository {

    public function getAll() {
        $em = $this->getEntityManager();
        $dql = "SELECT c obj,s.code tipo from UAHGestorActividadesBundle:Category c LEFT JOIN c.status s";
        $consulta = $em->createQuery($dql);
        return $consulta->getResult();
    }

    public function getParentCategories() {
        $em = $this->getEntityManager();
        $dql = "SELECT c from UAHGestorActividadesBundle:Category c LEFT JOIN c.status s WHERE c.status = :active_status and c.parent_category is NULL";
        $active_status = $em->getRepository('UAHGestorActividadesBundle:Statuscategory')->getActive();

        $consulta = $em->createQuery($dql);
        $consulta->setParameter('active_status', $active_status);
        return $consulta->getResult();
    }

}
