<?php

namespace UAH\GestorActividadesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StatusCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusCategoryRepository extends EntityRepository
{
    public function getActive()
    {
        $em = $this->getEntityManager();
        $dql = "SELECT sc FROM UAHGestorActividadesBundle:Statuscategory sc WHERE sc.code = 'STATUS_ACTIVE'";
        $consulta = $em->createQuery($dql);

        return $consulta->getSingleResult();
    }

    public function getInactive()
    {
        $em = $this->getEntityManager();
        $dql = "SELECT sc FROM UAHGestorActividadesBundle:Statuscategory sc WHERE sc.code = 'STATUS_INACTIVE'";
        $consulta = $em->createQuery($dql);

        return $consulta->getSingleResult();
    }
}
