<?php

namespace UAH\GestorActividadesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StatusDegreeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusDegreeRepository extends EntityRepository {

    public function getActive() {
        $dql = "SELECT sd from UAHGestorActividadesBundle:Statusdegree sd where sd.code = 'STATUS_RENEWED' or sd.code ='STATUS_NON_RENEWED'";
        $consulta = $this->getEntityManager()->createQuery($dql);
        return $consulta->getResult();
    }

    public function getRenewed() {
        $dql = "SELECT sd from UAHGestorActividadesBundle:Statusdegree sd where sd.code = 'STATUS_RENEWED'";
        $consulta = $this->getEntityManager()->createQuery($dql);
        return $consulta->getResult();
    }

    public function getNotRenewed() {

        $dql = "SELECT sd from UAHGestorActividadesBundle:Statusdegree sd where sd.code = 'STATUS_NON_RENEWED'";
        $consulta = $this->getEntityManager()->createQuery($dql);
        return $consulta->getResult();
    }

    public function getInactive() {

        $dql = "SELECT sd from UAHGestorActividadesBundle:Statusdegree sd where sd.code = 'STATUS_INACTIVE'";
        $consulta = $this->getEntityManager()->createQuery($dql);
        return $consulta->getResult();
    }

}
