CREATE TABLE UAH_GAT_ApplicationForm (
    id NUMBER(10) NOT NULL,	
    applicationDate TIMESTAMP(0) NOT NULL,	
    applicationFile BLOB NOT NULL,	
    verificationCode VARCHAR2(255) NOT NULL,	
    isProcessed NUMBER(1) NOT NULL,	
    userId NUMBER(10) DEFAULT NULL,	
    PRIMARY KEY(id));
CREATE INDEX UAH_GAT_PK_IDX_B5EFE7164B64DCC ON UAH_GAT_ApplicationForm (userId);
CREATE TABLE UAH_GAT_BasicRegistration (
id NUMBER(10) NOT NULL,	
dni VARCHAR2(255) NOT NULL,	
dateProcessed TIMESTAMP(0) NOT NULL,	
dateRegistered TIMESTAMP(0) NOT NULL,	
isProcessed NUMBER(1) NOT NULL,	
recognizedCredits DOUBLE PRECISION DEFAULT NULL,	
creditsType DOUBLE PRECISION DEFAULT NULL,	
activityId NUMBER(10) NOT NULL,	
idApplicationForm NUMBER(10) DEFAULT NULL,	
PRIMARY KEY(id));
CREATE INDEX UAH_GAT_PK_IDX_C80CFBBF1335E2FC ON UAH_GAT_BasicRegistration (activityId);
CREATE INDEX UAH_GAT_PK_IDX_C80CFBBF58344008 ON UAH_GAT_BasicRegistration (idApplicationForm);
CREATE TABLE UAH_GAT_Degree (
id NUMBER(10) NOT NULL,	
name VARCHAR2(255) NOT NULL,	
knowledgeArea VARCHAR2(255) NOT NULL,	
academicCode VARCHAR2(255) NOT NULL,	
PRIMARY KEY(id));
CREATE TABLE UAH_GAT_Activity (
id NUMBER(10) NOT NULL,	
organizer NUMBER(10) NOT NULL,	
name VARCHAR2(500) NOT NULL,	
englishName VARCHAR2(500) NOT NULL,	
numberOfECTSCreditsMin DOUBLE PRECISION NOT NULL,	
numberOfECTSCreditsMax DOUBLE PRECISION NOT NULL,	
numberOfCreditsMin DOUBLE PRECISION NOT NULL,	
numberOfCreditsMax DOUBLE PRECISION NOT NULL,	
isPublic NUMBER(1) NOT NULL,	
celebrationDates CLOB NOT NULL,	
hasAdditionalWorkload NUMBER(1) NOT NULL,	
numberOfHours DOUBLE PRECISION NOT NULL,	
assistanceControl VARCHAR2(255) NOT NULL,	
publicityStartDate DATE NOT NULL,	
registrationManagement NUMBER(1) NOT NULL,	
extraInformationFile BLOB NOT NULL,	
url VARCHAR2(255) NOT NULL,	
slug VARCHAR2(255) NOT NULL,	
numberOfPlacesOffered NUMBER(10) NOT NULL,	
numberOfPlacesOccupied NUMBER(10) NOT NULL,	
approvedByComitee NUMBER(1) NOT NULL,	
isActive NUMBER(1) NOT NULL,	
cost DOUBLE PRECISION NOT NULL,	
PRIMARY KEY(id));
CREATE INDEX UAH_GAT_PK_IDX_FA8719199D47173 ON UAH_GAT_Activity (organizer);
COMMENT ON COLUMN UAH_GAT_Activity.celebrationDates IS '(DC2Type:json_array)';
CREATE TABLE UAH_GAT_Activity_Degree (activityId NUMBER(10) NOT NULL,	
degreeId NUMBER(10) NOT NULL,	
PRIMARY KEY(activityId,	
degreeId));
CREATE INDEX UAH_GAT_PK_IDX_C8C9E83B1335E2FC ON UAH_GAT_Activity_Degree (activityId);
CREATE INDEX UAH_GAT_PK_IDX_C8C9E83B576EC1D0 ON UAH_GAT_Activity_Degree (degreeId);
CREATE TABLE UAH_GAT_User (
id NUMBER(10) NOT NULL,	
name VARCHAR2(255) NOT NULL,	
email VARCHAR2(255) DEFAULT NULL,	
type VARCHAR2(255) DEFAULT NULL,	
password VARCHAR2(255) NOT NULL,	
creationIp VARCHAR2(255) DEFAULT NULL,	
uahName VARCHAR2(255) DEFAULT NULL,	
degreeId NUMBER(10) DEFAULT NULL,	
PRIMARY KEY(id));
CREATE INDEX UAH_GAT_PK_IDX_8D0E506576EC1D0 ON UAH_GAT_User (degreeId);
CREATE TABLE UAH_GAT_User_Roles (user_id NUMBER(10) NOT NULL,	
role_id NUMBER(10) NOT NULL,	
PRIMARY KEY(user_id,	
role_id));
CREATE INDEX UAH_GAT_PK_IDX_E3EDAECCA76ED395 ON UAH_GAT_User_Roles (user_id);
CREATE INDEX UAH_GAT_PK_IDX_E3EDAECCD60322AC ON UAH_GAT_User_Roles (role_id);
CREATE TABLE UAH_GAT_Role (
id NUMBER(10) NOT NULL,	
name VARCHAR2(30) NOT NULL,	
role VARCHAR2(20) NOT NULL,	
PRIMARY KEY(id));
CREATE UNIQUE INDEX UAH_GAT_UniqueRole_idx ON UAH_GAT_Role (role);
CREATE SEQUENCE UAH_GAT_ApplicationForm_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1;
CREATE SEQUENCE UAH_GAT_BasicRegistration_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1;
CREATE SEQUENCE UAH_GAT_Degree_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1;
CREATE SEQUENCE UAH_GAT_Activity_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1;
CREATE SEQUENCE UAH_GAT_User_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1;
CREATE SEQUENCE UAH_GAT_Role_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1;
ALTER TABLE UAH_GAT_ApplicationForm ADD CONSTRAINT FK_B5EFE7164B64DCC FOREIGN KEY (userId) REFERENCES UAH_GAT_User (id);
ALTER TABLE UAH_GAT_BasicRegistration ADD CONSTRAINT FK_C80CFBBF1335E2FC FOREIGN KEY (activityId) REFERENCES UAH_GAT_Activity (id);
ALTER TABLE UAH_GAT_BasicRegistration ADD CONSTRAINT FK_C80CFBBF58344008 FOREIGN KEY (idApplicationForm) REFERENCES UAH_GAT_ApplicationForm (id);
ALTER TABLE UAH_GAT_Activity ADD CONSTRAINT FK_FA8719199D47173 FOREIGN KEY (organizer) REFERENCES UAH_GAT_User (id);
ALTER TABLE UAH_GAT_Activity_Degree ADD CONSTRAINT FK_C8C9E83B1335E2FC FOREIGN KEY (activityId) REFERENCES UAH_GAT_Activity (id);
ALTER TABLE UAH_GAT_Activity_Degree ADD CONSTRAINT FK_C8C9E83B576EC1D0 FOREIGN KEY (degreeId) REFERENCES UAH_GAT_Degree (id);
ALTER TABLE UAH_GAT_User ADD CONSTRAINT FK_8D0E506576EC1D0 FOREIGN KEY (degreeId) REFERENCES UAH_GAT_Degree (id);
ALTER TABLE UAH_GAT_User_Roles ADD CONSTRAINT FK_E3EDAECCA76ED395 FOREIGN KEY (user_id) REFERENCES UAH_GAT_User (id) ON DELETE CASCADE;
ALTER TABLE UAH_GAT_User_Roles ADD CONSTRAINT FK_E3EDAECCD60322AC FOREIGN KEY (role_id) REFERENCES UAH_GAT_Role (id) ON DELETE CASCADE;
